<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a>

# Защита данных клиентов

## Загрузка данных

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
#from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [4]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

In [5]:
features.shape

(5000, 4)

In [6]:
class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0

In [7]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.42494550286668


In [8]:
matrix = np.random.rand(4,4)
matrix

array([[0.81540184, 0.81459605, 0.2444119 , 0.75325912],
       [0.01889494, 0.71419133, 0.75738053, 0.50453302],
       [0.85411391, 0.46934874, 0.55360843, 0.44990733],
       [0.94421615, 0.35933402, 0.97232804, 0.7833209 ]])

In [9]:
np.linalg.inv(matrix)

array([[-0.15857509, -0.7722777 ,  1.70060305, -0.32684694],
       [ 0.16372506,  0.92926145,  1.80484989, -1.79260591],
       [-1.31555578,  0.73467628,  0.99787161,  0.21873054],
       [ 1.74902645, -0.40732289, -4.11649863,  2.22141477]])

## Умножение матриц

In [10]:
features_matrix = features @ matrix
features_matrix.head()

0             1             2             3
0  42366.584418  23310.153403  27491.247422  22337.625815
1  32458.142095  17868.464350  21072.932136  17120.470237
2  17936.940136   9877.035141  11647.741045   9462.685308
3  35618.835417  19587.559248  23103.321138  18773.297339
4  22293.717601  12270.814133  14470.631065  11757.461398

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

$$
Условие:
$$
Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

$$
Доказательство
$$

$$
w1 = ((XP)^T XP))^{-1} (XP)^T y
$$
$$
w1 = (P^T X^T  XP)^{-1} (XP)^T y
$$
$$
w1 = (P^T)^{-1} (X^TX)^{-1} (P)^{-1} P^T X^T  y
$$
$$
w1 = E (X^TX)^{-1}  (P)^{-1} X^T y
$$
$$
w1 = (P)^{-1}w
$$

$$
a1 = XP w1
$$

$$
a1 = XP (P)^{-1} w
$$
$$
a1 = Xw = a
$$

Как видно из доказательства новые предсказания будут равны старым предсказаниям, если домножить матрицу признаков на случайную обратимую матрицу.

## Алгоритм преобразования

1. Генерируем случайную квадратную матрицу
2. Проверяем случайную матрицу на обратимость. В случае, если матрица необратима, ее определитель равен нулю, что нам не подходит.
3. Домножаем случайную обратимую матрицу на признаки
4. Новой матрицей обучаем модель
5. Генерируем предсказания 
6. Сравниваем метрики R2. Если качесво не ухудшилось - все в порядке.

## Проверка алгоритма

In [11]:
matrix_2 = np.random.rand(4,4)
matrix_2

array([[0.33915964, 0.82286626, 0.02323332, 0.32114996],
       [0.42145684, 0.34908554, 0.80205629, 0.71105133],
       [0.02475361, 0.35408532, 0.247091  , 0.71608901],
       [0.06165115, 0.25000775, 0.60029792, 0.90266559]])

In [12]:
np.linalg.inv(matrix_2)

array([[ -4.84098887,   7.7850367 ,  15.20620127, -16.47328876],
       [  4.35513904,  -4.34356115,  -9.8582505 ,   9.692656  ],
       [  3.47079687,  -3.77328623, -12.66867088,  11.7875878 ],
       [ -3.18376833,   3.18065004,  10.11685396,  -8.29067418]])

In [13]:
features_2_matrix = features @ matrix_2

In [14]:
model_2 = LinearRegression()
model_2.fit(features_2_matrix, target)
predictions_2 = model_2.predict(features_2_matrix)
print(r2_score(target, predictions_2))

0.42494550285965405
