<div style="border: 1px solid #CCCCFF; border-radius: 1px;">
<div style="margin: 5px">
<b class="alert-heading">Комментарий ревьюера</b>
<p>Вадим, привет!</p>
<p>Меня зовут Алексей Секоцкий. Поздравляю с подготовкой очередного проекта. Предлагаю обращаться друг к другу на «ты» если нет возражений. Ниже стандартный блок с условными обозначениями:</p>
<div class="alert alert-success" role="alert">
всё отлично
</div>
<div class="alert alert-warning" role="alert">
рекомендации на будущее (не требующие доработки проекта)
</div>
<div class="alert alert-danger" role="alert">
критичные моменты требующие внимания (доработки)
</div>
<div class="alert alert-info">
итоговый комментарий
</div>

<hr>
<p>Пожалуйста, не изменяй и не удаляй мои комментарии – они потребуются для повторной проверки (при необходимости). Задавай вопросы и описывай сделанные изменения, помечая их любым удобным наглядным способом.</p>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span><ul class="toc-item"><li><span><a href="#Задача:" data-toc-modified-id="Задача:-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Задача:</a></span></li><li><span><a href="#Структура-проекта" data-toc-modified-id="Структура-проекта-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Структура проекта</a></span></li></ul></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
#from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [4]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

In [5]:
features.shape

(5000, 4)

<div class="alert alert-success">
<b>Комментарий ревьюера</b>

Отлично. Данные загружены и изучены.
</div>

In [6]:
class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0

In [7]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.42494550286668


In [8]:
matrix = np.random.rand(4,4)
matrix

array([[0.02298146, 0.32326339, 0.82288156, 0.08199258],
       [0.91351968, 0.67873161, 0.887689  , 0.63966969],
       [0.03504928, 0.66262399, 0.8969751 , 0.65172647],
       [0.99569968, 0.82260981, 0.7659769 , 0.3445032 ]])

<div class="alert alert-warning">
<b>Комментарий ревьюера</b>

При генерации матрицы желательно использовать seed (random_state) для ее воспроизводимости.
</div>

In [9]:
np.linalg.inv(matrix)

array([[ 0.02240528,  1.2319099 , -1.16681737, -0.0853598 ],
       [-1.15784696, -3.19573273,  1.7508882 ,  2.89706466],
       [ 1.79899828,  1.04752164, -0.7382399 , -0.97660014],
       [-1.29996986,  1.74120715,  0.83301571, -1.5968152 ]])

<div class="alert alert-warning">
<b>Комментарий ревьюера</b>

Весь код нужно перенести в 4 раздел.
</div>

## Умножение матриц

In [10]:
features_matrix = features @ matrix
features_matrix.head()

0             1             2             3
0  1776.917459  32895.123951  44527.949141  32352.285975
1  1374.890385  25211.756020  34126.653528  24795.375253
2   762.527028  13934.787082  18862.220112  13704.806337
3  1482.730443  27647.319116  37424.035155  27191.115961
4   940.387837  17313.813981  23436.728322  17028.053669

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

$$
Условие:
$$
Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

$$
Доказательство
$$

$$
w1 = ((XP)^T XP))^{-1} (XP)^T y
$$
$$
w1 = (P^T X^T  XP)^{-1} (XP)^T y
$$
$$
w1 = (P^T)^{-1} (X^TX)^{-1} (P)^{-1} P^T X^T  y
$$
$$
w1 = E (X^TX)^{-1}  (P)^{-1} X^T y
$$
$$
w1 = (P)^{-1}w
$$

$$
a1 = XP w1
$$

$$
a1 = XP (P)^{-1} w
$$
$$
a1 = Xw = a
$$

Как видно из доказательства новые предсказания будут равны старым предсказаниям, если домножить матрицу признаков на случайную обратимую матрицу.

<div class="alert alert-success">
<b>Комментарий ревьюера</b>

Доказательство верное. Весь код необходимо перенести в 4 раздел – проверка работы алгоритма у нас там. В данном разделе только теория.
</div>

## Алгоритм преобразования

1. Генерируем случайную квадратную матрицу
2. Проверяем случайную матрицу на обратимость. В случае, если матрица необратима, ее определитель равен нулю, что нам не подходит.
3. Домножаем случайную обратимую матрицу на признаки
4. Новой матрицей обучаем модель
5. Генерируем предсказания 
6. Сравниваем метрики R2. Если качесво не ухудшилось - все в порядке.

<div class="alert alert-success">
<b>Комментарий ревьюера</b>

Верно!
</div>

## Проверка алгоритма

In [11]:
matrix_2 = np.random.rand(4,4)
matrix_2

array([[0.89955339, 0.04821   , 0.40684417, 0.05130718],
       [0.54395291, 0.783269  , 0.14018981, 0.30667399],
       [0.38095576, 0.28084645, 0.12342341, 0.1414648 ],
       [0.73943153, 0.70942707, 0.78537828, 0.00952799]])

In [12]:
np.linalg.inv(matrix_2)

array([[  4.68228211,   6.11120923, -14.86688074,  -1.18002665],
       [  2.68448354,   6.98050544, -16.09910465,  -0.10664387],
       [ -6.68637951, -11.81642644,  27.87518847,   2.4655714 ],
       [-12.10487858, -20.00587306,  54.74541577,   1.23832407]])

In [13]:
features_2_matrix = features @ matrix_2

In [14]:
model_2 = LinearRegression()
model_2.fit(features_2_matrix, target)
predictions_2 = model_2.predict(features_2_matrix)
print(r2_score(target, predictions_2))

0.42494550286573674


<div class="alert alert-success">
<b>Комментарий ревьюера</b>

Верно! Собери весь код в данном разделе, пожалуйста.
</div>

<div class="alert alert-info">
<b>Итоговый комментарий ревьюера</b>

Отличный проект! Вспомнили свойства матриц, вывели формулу и освоили алгоритм шифрования. Желаю успехов в дальнейшем обучении! Впереди еще будут интересные задачи!
<hr>
</div>

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования

### Задача:
Разработать алгоритм защиты данных клиентов таким образом, чтобы качество модели машинного обучения не ухудшилось.
В качестве метрики качества используется R2. В качестве модели машинного обучения используется LinearRegression

### Структура проекта
* Загрузка данных
* Умножение матриц / математическое обоснование решения
* Алгоритм преобразования
* Проверка алгоритма